### ISSUE TITLE
Create Drop Box Package

### ISSUE THREAD

**Issue by aembler** [concrete5/drop_box#1]
The drop box package is meant to allow users to upload large files and share them easily. The original requirements are:

* Create a destination that will allow users with appropriate access to upload large files (up to
30GB). 
* Each upload shall be accessible through a unique public download URL that has to be manually shared.  
* Files shall automatically be removed and expire after 45 days.
* These dropbox files should be organized in a way where admins can see a list of all the currently available ones.
* Admins should be able to control via permissions who has the ability to create a new dropbox file.  (they will allow garrisons to do this from time to time)
* Uploading of large files over HTTPS will be a concern and we should do our best to make sure this works smoothly. 

I'm thinking this should be a custom concrete5 package installable via composer that adds the components to make this run smoothly, from a front-end and back-end perspective. 

Create package that installs via composer. Should have a composer.json and installs the relevant entities, single pages, controllers, and endpoints. (Note: at the beginning of the project this doesn't need to have any of this, it just needs to be set up so that this can be added over time.) https://github.com/concrete5/cloudfront_proxy Is a good example of a simple concrete5 package that installs via composer.

Set up composer autoloading at `Concrete5\Dropbox` that points to packages/drop_box/src.

Version 1.0 of the Drop Box package should feature the following functionality. 

* A doctrine ORM entity at packages/drop_box/src/Entity/UploadedFile.php. This should use a GUID/UUID file as its primary identifier, a separate UUID/GUID that's private as its fileIdentifier, along with an original filename (a string), a unix timestamp of when the file was uploaded, and a description field. Let's also join it to the `Concrete\Core\Entity\User\User.php` entity (but make this nullable.)
* Let's create a block type called Dropbox. You can add this to the page. This should use custom JavaScript that enables a nice interface with a progress bar. It should *not* use dropzone; instead, build a custom JS client using https://github.com/tus/tus-js-client so we can handle large uploads.
* Any endpoint that TUS JS Requires let's use the routing/controller system in concrete5 to add these routes to the Dropbox package. 
* Add a new "Upload File to Dropbox" custom permission that's accessible from the file permissions dashboard page. Use this permission when uploading through the dropbox block. 
* Let's add a Dashboard > System and Settings > Files > Dropbox Settings dashboard page where we can put any settings that we need to to make this configurable. 
* Uploading files through this dropbox should store them in a secure location on the server. This should be configurable through the Dropbox Settings dashboard page.
*  Add a new Dashboard page at Dashboard > Files > Dropbox. Use the styles of the File Manager, Logs, Page Search, etc... to make this look nice. It should show all uploaded files and let administrators get the public URL of the file, as well as delete the file.

**Comment by bitterdev** [comment]
@aembler Because of the further implementation i have 2 questions. I can use the concrete5 file manager to store the files and reference the UploadedFile to a file object. Then you don't need to add fields like description, original file name etc. I could use custom attributes for this and fill the attributes when uploading a file through the block. Furhtermore the c5 file manger supports multple storage locations like S3 buckets (with 3rd party libraries) which is great for storing large files. Currently i have implemented this way. The UploadedFile entity just have the fields primaryGuid, fileGuid, file, createdAt. (Btw: Can you please give me the correct naming for the both guid fields?). But if you want i can implement this entity completly independent from the c5 file manager and add all your required fields and store the files to the given path from the settings. What do you prefer? Best wishes Fabian

**Comment by aembler** [comment]
This issue is complete.
